### ISSUE TITLE
README Feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#40]
- Instructions should read python instead of python3 - otherwise script may not run
- README should include high-level overview of the project
- README should include dependencies
- Cite at least one external sources other than data source, languages, and packages.

**Comment by slbsolomon** [comment]
Assignments:
@slbsolomon: Instructions should read python instead of python3 - otherwise script may not run
@EitharAlfatih: README should include high-level overview of the project
@EitharAlfatih: README should include dependencies
@slbsolomon: Cite at least one external sources other than data source, languages, and packages.

**Comment by slbsolomon** [comment]
Updated in #50:
- all of us are on Macs so all of us do run it with python3, nonetheless we updated it to python in the readme

**Comment by ksedivyhaley** [comment]
Ah, OS issue. Is python3 the required command for macs, or can you use either?

**Comment by EitharAlfatih** [comment]
It seems both works fine.
Changes are applied to README.md

**Comment by slbsolomon** [comment]
thanks Eithar! confirmed it works for me as well for this script....I believe that some scripts do require specification (my DSCI 542 script did require this spec)
