### ISSUE TITLE
Samantha's Class Feedback

### ISSUE THREAD

**Issue by slbsolomon** [UBC-MDS/DSCI_522_GROUP_312#47]
- more runs with knn to try and take out some features to address multicollinearity
- correlation heatmap: make more human readable labels
- considera generalised linear model
- change tables to charts

**Comment by gptzjs** [comment]
- agreed: we will do more runs of knn with different combinations of features (Eithar)
- agreed: we will update the labels accordingly (George)
- disagree: due to time and resource constraints and better initial performance of knn over linear regression, we will stay focused on improving knn versus trying glm (N/A)
- agreed: will change the linear regression and knn tables to charts (Eithar)

**Comment by slbsolomon** [comment]
All updated in #52
