### ISSUE TITLE
Milestone 3: Viz feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_GROUP_312#60]
Good improvements to plots based on feedback! A few things to consider for Milestone 4:

- The new plots are good, but it would be better to arrange them side by side.
- First table could still stand to have more reader-friendly column names (particularly, VIF instead of vif_val).
- As mentioned in #44, for Milestone 4 I will expect that the correlation plot diagonal should have its value set to 0 or NAN to give a less overpowering colour.
- From #48, I'd like to see some way of comparing actual vs predicted prices! Could you do this with [density plots](http://www.sthda.com/english/articles/32-r-graphics-essentials/133-plot-one-variable-frequency-graph-density-distribution-and-more/)?

**Comment by slbsolomon** [comment]
Assignments are as follows:
- The new plots are good, but it would be better to arrange them side by side. - @slbsolomon 
- First table could still stand to have more reader-friendly column names (particularly, VIF instead of vif_val). - @slbsolomon 
- As mentioned in #44, for Milestone 4 I will expect that the correlation plot diagonal should have its value set to 0 or NAN to give a less overpowering colour. - @gptzjs (there is already an issue open for this which George will update that issue when it is done)
- From #48, I'd like to see some way of comparing actual vs predicted prices! Could you do this with density plots? - @slbsolomon

**Comment by gptzjs** [comment]
I have already created a new correlation plot addressing all these issues which is contained in my last PR

**Comment by slbsolomon** [comment]
Hi Kate,

I am having some issues putting the visualizations side by side in the report (it is a Jupyter notebook). I have made all of the charts the same size, but that doesn't seem to make the png images the same size so when I try and put them side by side they are different sizes and then the text gets wrapped.

An example of what I put in the markdown (but 2 of these):
<img src="ml_results/LR_performace.png" width="50%" align="left"/>

Unless you know of another solution to try, we will not put the images side by side because I would consider the text wrapping to be more of an issue than having the images stacked.

**Comment by ksedivyhaley** [comment]
I received an email notification of an update in this issue saying that you were having trouble placing the figures side by side in the Jupyter notebook. Since I'm not seeing that post, I'm hoping it's resolved - if not, I recommend posting in slack.

**Comment by slbsolomon** [comment]
Hi Kate,

All of these items have been addressed in #73
